### ISSUE TITLE
Make a good readme file so that contributors may know the purpose of this repo.

### ISSUE THREAD

**Issue by ANKIT9761** [devnest-coders/Projects#7]
So this repo is made for people who are willing to submit their development project as an open source contribution for hacktoberfest.
A person should first create a folder of his name then make subdirectories for his/her projects.
You can ask for code reviews and code improvement also while creating a pull request we will review your code and give you feedabck on it.
And at last try contributing as much as possible don't hesitate to upload any project be it as a starter project or anything. The first thing is to get started and take help.
Happy hacking people

**Comment by raelimasina** [comment]
Hello! I have four years of technical writing experience, and would love to create a readme for this repo. Could you assign it to me?

**Comment by ANKIT9761** [comment]
Sure @raelimasina i will assign it to you.Thanks for responding 🙌.
